### ISSUE TITLE
Clarify help text for project and instance parameters

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/azure-devops-cli-extension#100]
The in-product help (i.e. `--help`) and the docs indicate that `--project` and `--instance` are optional arguments in many calls, but this is only true if `--detect on` is passed and the CLI is able to detect the project and instance from the local Git directory.

We should clarify the help text for both of these arguments to explain when one or both is required, and refer to the detect option. Also may need to update the error text shown by the CLI when no project is supplied.

**Comment by bergmeister** [comment]
I found it very confusing when I first started using the cli. `detect` should be enabed by default and on the first command after the installation, if it cannot detect the project/instance, then it should ask the user if he/she wants to configure defaults. Only after 15 minutes when I got too annoyed, I had to look up how to set the defaults.

**Comment by tedchamb** [comment]
@bergmeister ,  --detect is enabled by default.  It just has no effect if your current working directory is not associated with a git repo.  Did you experience something different?

**Comment by atbagga** [comment]
VSTS CLI is now Azure DevOps Extension. Refer the repo readme for more details. 

We have updated the help texts and getting started guides to educate the new users on setting defaults including setting the defaults implicitly if you login with a particular organization. 

Hopefully that fixes this and any similar issues that the users were facing. 

e.g. Updates Error messages look like below:
"--organization must be specified. The value should be the URI of your Azure DevOps organization, for example: https://dev.azure.com/MyOrganization/ or your TFS organization. You can set a default value by running: az devops configure --defaults organization=https://dev.azure.com/MyOrganization/. For auto detection to work (--detect on), you must be in a local Git directory that has a "remote" referencing a Azure DevOps or TFS repository."
AND
"--project must be specified. The value should be the ID or name of a team project. You can set a default value by running: az devops configure --defaults project=<ProjectName>."

Hence closing the issue.
