### ISSUE TITLE
Extension management commands

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/azure-devops-cli-extension#103]
Commands to manage installed extensions in a VSTS account or TFS project collection. 

> Note these commands are not for packaging or publishing extensions, only managing extensions that have already been published to the Marketplace/Gallery.

# Proposed design

## List installed extensions

```
vsts extension list
```

### Optional arguments

* `--include-built-in`. Include built-in extensions in the results.
** Implementation note: the CLI will need to manually remove extensions from the response that have the "builtin" flag if the caller does not want to get installed extensions. There is no REST API parameter for this, but the normal case is to not show built-in extensions since they can't really be managed).
* ` ---include-disabled`: Include installed extensions that are currently disabled in the results.

## Show, install, or uninstall an extension

```
vsts extension show --id {publisherId.extensionId}
vsts extension install --id {publisherId.extensionId}
vsts extension uninstall --id {publisherId.extensionId}
vsts extension enable ---id {publisherId.extensionId}
vsts extension disable --id {publisherId.extensionId}
```

## Table columns for commands that return a response (i.e. all but "uninstall")

* ID (combines publisher ID plus "." plus extension ID)
* Name ("Team Calendar")
* Publisher ("Microsoft DevLabs")
* Version ("0.3.1")
* Last Updated (a date/time)
* States (enabled or disabled)
* Flags (comma-separated list .. if "none", don't show anything -- leave column blank)

**Comment by masters3d** [comment]
A use case for uninstall for extensions for VSTS: The market place takes a few minutes to push updates to all installed accounts. 

New installs seem to always use the newest version on the market place so when I am developing a extension for VSTS, it is ideal to force a reload of that extension so I can do further testing.

In my case, I would pair an uninstall before an install to force a refresh. 

Alternatively, The install command should force this refresh?

**Comment by gauravsaralMs** [comment]
Closing this because the command mentioned/required here are done
