### ISSUE TITLE
Build Task with online vsts CLI commands

### ISSUE THREAD

**Issue by jerickmsft** [Microsoft/azure-devops-cli-extension#112]
Just like how there are tasks for powershell and batch script commands, I would love one for VSTS CLI commands. The key being that the task would download the CLI as needed, so I don't need to worry about keeping it updated and so hosted agents can use it.

**Comment by tedchamb** [comment]
Our current plan is to add a task to install the vsts cli, then you can leverage it from a cmd or batch script task.  This is similar to the node.js.

**Comment by geverghe** [comment]
With the move from VSTS CLI to Azure DevOps extension to Azure CLI, you can use simply "add" the extension to the latest Azure CLI version available on the agent. This will pull the latest extension version by default.

Further, you can also implement the same using a powershell script task. Here is a [sample](https://github.com/Microsoft/azure-devops-cli-extension/blob/master/doc/samples.md#use-the-azure-devops-extension-in-a-release-pipeline) of how the azure devops extension is added to an azure cli installation in a release pipeline.
