### ISSUE TITLE
generate_command_inventory.py --params

### ISSUE THREAD

**Issue by dfinke** [Microsoft/azure-devops-cli-extension#126]
I get the following error when I try this ` python .\generate_command_inventory.py --commands build --params list`

```
Traceback (most recent call last):
  File ".\generate_command_inventory.py", line 57, in <module>
    cmd_args = cmd_table[cmd_name]['arguments']
TypeError: 'CLICommand' object is not subscriptable
```

Am I using it correctly. Optimally, I'd like to get all the commands back and all the parameters for that command but this ` python .\generate_command_inventory.py` only brings back the cmds.

![image](https://user-images.githubusercontent.com/67258/34342736-747ffe1c-e987-11e7-9043-9001d264882e.png)

**Comment by tedchamb** [comment]
@willsmythe Can you take a look at this question?

**Comment by dfinke** [comment]
I was able to re-work the `generate_command_inventory.py` a little and I am code generating these PowerShell function wrappers with params etc.

The `generate_command_inventory.py` was not pulling back the arguments, the ones I'm getting now are still not 100%. If I could get guidance on how to gather the commands, args and help, I can code gen the PS functions, and it would be super helpful to use the `vsts-cli` wrappers from PS.

Thanks!

https://gist.github.com/dfinke/0a948cc9a014d3e46aba4fc851b4945a

**Comment by willsmythe** [comment]
@dfinke - see linked PR. It updates the inventory script to produce a JSON-formatted inventory of CLI commands and arguments. Is there other metadata you need?

**Comment by dfinke** [comment]
Thanks. Can the attribute for an argument be exported if it is "required"? Also, I think some args like `definition_id` are passed as `id` on the cli. I'd need a map of that so I can translate the parameter to the name needed by vsts-cli.

**Comment by dfinke** [comment]
Coming together. If I can get a few more details about the args, if they're required, the actual name that `vsts` expects. I can take this map in PowerShell and transpile it. I believe it'll be super useful to call `vsts` from PS using functions and it's object flow engine.

```powershell
$data = python .\generate_command_inventory.py | ConvertFrom-Json

$list=[ordered]@{}
foreach($name in $data.psobject.properties.name|sort) {
    $list.$name=$data.$name
}

$list
```

![image](https://user-images.githubusercontent.com/67258/35407006-7a029ce6-01d8-11e8-8f9a-63be6a5315e4.png)

**Comment by geverghe** [comment]
[We recently announced the release of the Azure DevOps extension to Azure CLI](https://devblogs.microsoft.com/devops/using-azure-devops-from-the-command-line/). We will not be investing in features in VSTS CLI.
