### ISSUE TITLE
Feature request: Repository update (Allow to set default branch, rename repo)

### ISSUE THREAD

**Issue by Tantino** [Microsoft/azure-devops-cli-extension#147]
**Proposed Command Structure:** 

**az repos update** : Update the repository 

    --detect             : Automatically detect organization, project and repository. Default is
                           "on".  Allowed values: off, on.
    --repository -r    : Name or ID of the repository.
    --org --organization : Azure Devops organization URL. Example:
                           https://dev.azure.com/MyOrganizationName/.
    --project -p         : Name or ID of the team project.
    --default-branch  : Branch name to be set as default. For setting master as default use 'master' or 'refs/heads/master'
    --name                 : New name of the repository 

**API doc:** https://docs.microsoft.com/en-us/rest/api/azure/devops/git/repositories/update?view=azure-devops-rest-4.1

**Original Request:**
Hi,

Can you add an ability to set default branch for `repo`?

Thanks and regards

**Comment by atbagga** [comment]
Added repo update command in Azure-devops-Extension. Will be available in version 0.3.0
