### ISSUE TITLE
MicroSoft Container for this please

### ISSUE THREAD

**Issue by ATXGearHead12** [Microsoft/azure-devops-cli-extension#158]
I think it is great that you created a lynx docker image on docker.hub for this.    Would love to see a windows container docker image on docker.hub for this.

**Comment by geverghe** [comment]
Considering our move to provide the command line experience via Azure DevOps Extension to Azure CLI, we will not be supporting VSTS CLI images. Azure CLI supports a [linux docker image](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker?view=azure-cli-latest).
