### ISSUE TITLE
Feature request: vsts build definition create

### ISSUE THREAD

**Issue by docunid** [Microsoft/azure-devops-cli-extension#162]
vsts-cli/src/command_modules/vsts-cli-build/vsts/cli/build/commands.py

**Comment by geverghe** [comment]
@docunid - [We released the Azure DevOps extension to Azure CLI ](https://devblogs.microsoft.com/devops/using-azure-devops-from-the-command-line/) and will not be investing in vsts cli. At present we are working on supporting YAML pipelines from CLI (#333) inclduing creation of a pipelines. Let me know if that works for you.

**Comment by docunid** [comment]
that'll work :)
