### ISSUE TITLE
Feature Request: Add/remove/update users for GIT repositories

### ISSUE THREAD

**Issue by lewnewby** [Microsoft/azure-devops-cli-extension#165]
I would like to leverage security controls to add/remove/update users on specific GIT repositories. 

The purpose is to create multiple repositories within a project each of them with a different owner and defaulting to limited or no access for others in the team AKA "Private Repositories"

I am going to try and take a stab at this myself.

**Comment by geverghe** [comment]
@lewnewby - Would #471 suffice your need?

**Comment by lewnewby** [comment]
Yes, looks like it would

**Comment by geverghe** [comment]
Closing this issue as duplicate of #471 to track all feedback on one thread.
