### ISSUE TITLE
Feature Request: Add build tag via cli

### ISSUE THREAD

**Issue by whihathac** [Microsoft/azure-devops-cli-extension#215]
In addition of creating builds via CLI, it will indeed be great if we can update build tags while creating or after the fact it's created

**Comment by snankani** [comment]
We have migrated the cli commands to Azure DevOps Extension for Azure CLI. We are planning to add pipeline tag command in Azure DevOps CLI extension. Tracking #333 

Hence closing the issue.

**Comment by whihathac** [comment]
@snankani - Is adding pipeline tag same as adding tag for a specific build?

**Comment by geverghe** [comment]
@whihathac - Yep it will be tagging a specific build. The command we are planning to build is 
`az pipelines build tag --build-id` where build ID is the ID corresponding to a specific build.
