### ISSUE TITLE
Format for Add Banner option expiration date

### ISSUE THREAD

**Issue by OsirisTerje** [Microsoft/azure-devops-cli-extension#225]
Hi !

1.  An expiration date can take many forms.  What is the correct format to use here?

2. In general, all commands and all their options should have examples

regards
Terje

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2defa5-f976-2d8b-0d23-4af1eecf43e3
* Version Independent ID: efa5d010-ffb5-9113-3b3a-dff60c160cd7
* Content: [vsts admin banner](https://docs.microsoft.com/en-us/cli/vsts/admin/banner?view=vsts-cli-latest#vsts-admin-banner-add)
* Content Source: [src/command_modules/vsts-cli-admin/vsts/cli/admin/_help.py](https://github.com/Microsoft/vsts-cli/blob/master/src/command_modules/vsts-cli-admin/vsts/cli/admin/_help.py)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by tedchamb** [comment]
We call [dateutil.parser.parse(value)](https://github.com/Microsoft/vsts-cli/blob/d7758e9ab44657c66bf2149e62648384b78360a2/src/common_modules/vsts-cli-common/vsts/cli/common/arguments.py#L35) on your date string.  It will except a wide variety of formats.

Docs on dateutil.parser.parse:
https://dateutil.readthedocs.io/en/stable/parser.html

These examples show some valid formats:
https://dateutil.readthedocs.io/en/stable/examples.html#parse-examples

**Comment by gauravsaralMs** [comment]
getting fixed in https://github.com/Microsoft/azure-devops-cli-extension/pull/371

**Comment by snankani** [comment]
Issue is fixed and will be available in next release azure devops extension for azure cli 0.3.0
