### ISSUE TITLE
Command to see/tail Build logs 

### ISSUE THREAD

**Issue by melezhik** [Microsoft/azure-devops-cli-extension#235]
I'd like to see/tail logs for a certain build. Is is possible through vsts cli?

Thanks

**Comment by atbagga** [comment]
@melezhik This functionality is currently not supported through vsts-cli. We will take this as an enhancement request.

**Comment by snankani** [comment]
We have migrated the cli commands to Azure DevOps Extension for Azure CLI. We are planning to add show logs command in Azure DevOps CLI extension. Tracking #377 

Hence closing the issue.
