### ISSUE TITLE
Feature Request: Implement PR checkout

### ISSUE THREAD

**Issue by giggio** [Microsoft/azure-devops-cli-extension#249]
I should be able to checkout a PR by using `git pr checkout --id 3`.

**Comment by atbagga** [comment]
@giggio Can you give a more details on what functionality you want and what purpose it serves in the azure devops (vsts) flow?

**Comment by giggio** [comment]
Yes. Somebody creates a PR. I will review it. I am on my terminal. I list the pull requests, find the one I have to review, and issue the command `git pr checkout --id 3`. The tool fetches the branch and checks it out on my local repo. After I am done, I vote on it.

**Comment by gauravsaralMs** [comment]
Closing as this is done

**Comment by giggio** [comment]
It seems that the command will be `az repos pr checkout`, for anyone following this issue. I just checked version 0.4.0 and it is not there yet.
Any idea of when this is going to be released?

**Comment by gauravsaralMs** [comment]
@giggio : This command will be part of 0.5.0 release, but we don't have a date for that release.
You can still try it from edge build
```
C:\>az extension remove -n azure-devops

C:\>az extension add --source https://azuredevopscli.blob.core.windows.net/azuredevopscli/azure_devops-0.5.0-py2.py3-none-any.whl -y
```
