### ISSUE TITLE
--assigned-to throwing "Identity Value 'X' for field 'Assigned to' is an unknown identity

### ISSUE THREAD

**Issue by Gander7** [Microsoft/azure-devops-cli-extension#272]
`vsts work item create --title "Test Title" --type "Bug" --assigned-to "user@company.com"`
throws following error
`The identity value 'XXXXXXXXXXXXXXXXXXX@Live.com' for field 'Assigned To' is an unknown identity.`

I've tried different formats for --assigned-to
- `Windows Live ID\\user@company.com`
- `user@company.com`
- `Full Name`

Throws error regardless of type or title.
I've tried various users in case it was a specific user.

Any thoughts or workarounds? We are trying to migrate to devops and this is a breaking issue for us :(

**Comment by atbagga** [comment]
I only see "The identity value 'user-alpha@Live.com' for field 'Assigned To' is an unknown identity." when user-alpha does not have valid project/organization membership.

I have tried all the three formats like.. 
1. user-name@organization-name.com
2. user-name
3. "FirstName LastName"

and they work for me for a valid user. 

Can you try creating a workitem in the UI and assign to the same user as you are trying from CLI to help us troubleshoot further.

**Comment by snankani** [comment]
@Gander7 We are looking for your reply to help you better. Request to take some time and let us know if the above suggested steps work for you. 

FYI, we have migrated to Azure DevOps extension which is an extension to Azure CLI. Please find details here https://github.com/Microsoft/azure-devops-cli-extension/blob/master/README.md

**Comment by ishitam8** [comment]
We were able to reproduce this issue. Hence, reopening this.
