### ISSUE TITLE
Can't set state of work item to done with `vsts work item create`

### ISSUE THREAD

**Issue by Gander7** [Microsoft/azure-devops-cli-extension#273]
I am migrating a project into devops and need to be able to set a work item to Done when I create it. We are using scrum so according to the [workflow states](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/workflow-and-state-categories?view=vsts), Done is a valid state.

`vsts work item create --title "title" --type "Product Backlog Item" --state Done`
throws
`The field 'State' contains the value 'Done' that is not in the list of supported values.`

There is no documentation or code of the "list of supported values" that I can find.
In this repository, the only spot I found a similar enum was in `src\command_modules\vsts-cli-team\vsts\cli\team\arguments.py`
```
_STATE_VALUES = ['invalid', 'unchanged', 'all', 'new', 'wellformed', 'deleting', 'createpending']
```
Unfortunately, after trying them all, the only one that didn't throw an error was "new"

The example in the [docs](https://docs.microsoft.com/en-us/cli/vsts/work/item?view=vsts-cli-latest#vsts-work-item-create) (active) throws the same error as well.

Is there a supported list of state values that I have overlooked?

**Comment by ishitam8** [comment]
Hi @Gander7  ,

The _STATE_VALUES you mentioned are for new project creation and not work item creation.
Currently only one state is supported at the time of work item creation i.e 'New'.
I would suggest you run 2 consecutive commands if you need to set a newly created WIT state to 'Done'.
 1. vsts work item create --title "title" --type "Product Backlog Item" 
 Fetch id from result of above command and use this to update the state from 'New' to 'Done' 
 2. vsts work item update --id XX --state "Done"

The documentation mentions 'Active' as a valid state which is incorrect. Thanks for pointing that out. We would surely fix the documentation.

**Comment by atbagga** [comment]
@Gander7 Different workitem types have different valid value for the state field. Of all the valid states for a work-item type there is a limited set of values you can set to while creating a work-item. See sample screenshots below- 

e.g. 
![image](https://user-images.githubusercontent.com/11888714/50888274-4e30bc00-141b-11e9-9779-4258a36396e1.png)

![image](https://user-images.githubusercontent.com/11888714/50888227-30635700-141b-11e9-8dfb-32afe33d26ca.png)

![image](https://user-images.githubusercontent.com/11888714/50888814-7b319e80-141c-11e9-93dc-49799fb7b550.png)

On top of this there can be custom workitem types for which a user defines the valid state values. So this is hard to document. As a workaround you can check the list of valid values from the UI dropdown for the workitem type you are interested in. 

As shown above valid values for type "Product Backlog item" are ('new', 'done', 'approved', 'committed', 'removed') 

But while creating a new "Product Backlog item" only new is a valid state. 


Hope this resolves the issue for you.

**Comment by snankani** [comment]
It has been a while we heard from you. We hope the details provided above answers your question and should unblock you. 

We are closing this issue. If you feel you need more info or any further action is required from our end then please feel free to reopen the issue.
