### ISSUE TITLE
[Bug] Azure cli ext generates wrong documentation due to mismatching parameter names in commands

### ISSUE THREAD

**Issue by atbagga** [Microsoft/azure-devops-cli-extension#354]
e.g. https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/build/definition?view=azure-cli-latest

The parameter --devops-organization  should be --organization

**Comment by gauravsaralMs** [comment]
same is true for places where we are using open_browser
basically we should not add something like this 
context.argument('devops_organization', options_list=('--organization', '--org'))

options_list should always contain real argument name so that help text and documentation are in sync

**Comment by atbagga** [comment]
Raised a PR #355 To fix for both --devops-organization and --open-browser
