### ISSUE TITLE
[Bug] : Update dev set up documentation, verify scripts in scripts folder

### ISSUE THREAD

**Issue by geverghe** [Microsoft/azure-devops-cli-extension#361]
**Describe the bug**
1. Sanity check of the dev set up documentation. Remove VSTS references in the doc.
2. Sanity check of scripts in the scripts folder. Remove scripts that are not applicable.
3. Evaluate if we can include all 4 azure pipelines in the ".azure-pipelines" folder at the root. 

**To Reproduce**
NA

Azure-Devops extension version: 
NA

NA

**Expected behavior**
NA

**Screenshots**
NA

**Debug logs**
NA

**Additional context**
NA

cc: @willsmythe, @snankani

**Comment by atbagga** [comment]
#366 from @gauravsaralMs takes care of moving yamls to pipelines folder 
Raised a PR #368 for removing all occurrences of vsts-cli and removing unwanted scripts.
