### ISSUE TITLE
Add markdown lint check in PR pipeline

### ISSUE THREAD

**Issue by atbagga** [Microsoft/azure-devops-cli-extension#387]
#383 This PR fixes the lint issues in all MD files. We should add a check in PR pipeline to avoid such issues creep in the repo again in future.

**Comment by geverghe** [comment]
@atbagga Can we close this or has to wait till next release?

**Comment by atbagga** [comment]
This is not yet in. We are reworking on all scripts to be both developer environment friendly and pipeline friendly as well. So this one was on hold.

This task is just for setting up the pipeline so it does't have to be tied to a release.

**Comment by gauravsaralMs** [comment]
This is done
