### ISSUE TITLE
Convention to be used for params in rename or update commands 

### ISSUE THREAD

**Issue by atbagga** [Microsoft/azure-devops-cli-extension#388]
What should be the convention when updating a artifact with new name or new description?
The confusion is regarding whether that param is an identifier or update param. 
e.g. az repos update --repository XYZ --name XYZ_updated

Should we prepend new to it? 

There are couple of instance as far as i know of this as of now.. repos update and team update commands.

**Comment by geverghe** [comment]
I see that you have gone with latter. Closing this.
