### ISSUE TITLE
Improve live test infra - Make tests independent of the organization to run on 

### ISSUE THREAD

**Issue by atbagga** [Microsoft/azure-devops-cli-extension#395]
Our current recording tests run on the fixed test org due to dependency on pre-setup for the tests, which makes it difficult for outside contributors to write recording tests. 

We want to write tests such that they run independently without using existing setup in the test org.

This task will include - 

1. Allow each test to run against different org for recording and same org for live run
1. Make each test independent of the setup i.e. each test should start with creating a new project and work through creating desired devops resources to be tested.

**Comment by geverghe** [comment]
Closing this since it is completed.
