### ISSUE TITLE
[Feature Request] Add users via CLI

### ISSUE THREAD

**Issue by bhoobal** [Microsoft/azure-devops-cli-extension#411]
I would like to manage users through CLI (Add/remove users)
I should be able to add users, their access level ,Projects, groups and extension assignments.
This would make secure and quick way to board and off board users.

**Comment by atbagga** [comment]
@bhoobal This is already planned see issue #102. 
Please feel free to add comments or +1 in that one and follow that issue for updates. 

I am closing this as duplicate.

Thank you for showing interest in the project and for your contribution by raising a issue. 👍
