### ISSUE TITLE
Remove dependency from 4.0 azure devops client

### ISSUE THREAD

**Issue by gauravsaralMs** [Microsoft/azure-devops-cli-extension#416]
https://github.com/Microsoft/azure-devops-cli-extension/blob/master/azure-devops/azext_devops/dev/common/services.py 

All v4_0 should be moved to v4.1

**Comment by snankani** [comment]
I feel we should move to latest version once we get the new sdk for pipelines commands.

**Comment by gauravsaralMs** [comment]
> I feel we should move to latest version once we get the new sdk for pipelines commands.

makes sense
fyi: @atbagga as we will need to align this with pipeline work

**Comment by atbagga** [comment]
#492

**Comment by gauravsaralMs** [comment]
@atbagga : Should we close this now?
