### ISSUE TITLE
Add Security related command in DevOps CLI

### ISSUE THREAD

**Issue by gauravsaralMs** [Microsoft/azure-devops-cli-extension#418]
Provide Security related commands 
https://docs.microsoft.com/en-us/rest/api/azure/devops/security/?view=azure-devops-rest-5.0 

Issues:
[Please go through the above link then only this will make sense]

1. Security Namespace does not define how token is created and there is no way to fetch the same
example: for git repository the token looks like this
'repoV2/<<project Id>>/<<repo Id>>
so it will not be possible for user to understand how to construct this token for all the different namespace.
we can document all this into our help text but that will be a multi-sprint effort because there are ~ 60 namespaces in Azure DevOps currently.
https://dev.azure.com/ms/_apis/securitynamespaces/?api-version=5.0 

2. The permission management APIs take descriptor as input to provide input, while I am able to understand how can we get descriptor for AD identities I am not sure how to do this for VSTS groups.

**Comment by gauravsaralMs** [comment]
assigning to @geverghe  and @snankani to triage

**Comment by geverghe** [comment]
When you mean security related commands - what are the scenarios that are being tackled?

**Comment by gauravsaralMs** [comment]
> When you mean security related commands - what are the scenarios that are being tackled?

Permission scenarios mainly
https://docs.microsoft.com/en-us/rest/api/azure/devops/security/?view=azure-devops-rest-5.0

**Comment by geverghe** [comment]
Closing this as security group is being tackled is #471 and permissions in #472. Please let me know if there is something that has been missed.
