### ISSUE TITLE
Also include instruction on how to compare the SHA256 hash 

### ISSUE THREAD

**Issue by mydiemho** [Microsoft/azure-devops-cli-extension#420]
There's instruction on how to generate the SHA256 hash of the downloaded file, but there isn't instruction on how to compare the hash

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29493ec8-b119-457b-21c1-348a6b807884
* Version Independent ID: bf64c389-7811-b33c-6c2a-b8d69a9ec7d3
* Content: [Install the VSTS CLI](https://docs.microsoft.com/en-us/cli/vsts/install?view=vsts-cli-latest#install-on-linux)
* Content Source: [latest/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/vsts-docs-cli-python/blob/live/latest/docs-ref-conceptual/install.md)
* Product: **vsts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by atbagga** [comment]
The Azure CLI with the Azure DevOps extension has replaced the VSTS CLI. The VSTS CLI has been deprecated and will no longer be receiving new features. We recommend that users of the VSTS CLI switch to the Azure CLI and add the Azure DevOps extension. 

This issue should no longer be a concern if you use the Azure DevOps extension.

Still to answer your question: 
Comparing the hash is to compare it against the published value on the blog for the latest version. 
![image](https://user-images.githubusercontent.com/11888714/52341802-99011c00-2a39-11e9-8c32-87fa914d29b5.png)

If this is linked to your question on how to do so automatically or non interactively then there is no support for that.

**Comment by atbagga** [comment]
@mydiemho Thank you for the feedback. 
Closing the issue as per above comment and discussion on #421.
