### ISSUE TITLE
Feedback not working on docs.microsoft.com

### ISSUE THREAD

**Issue by mydiemho** [Microsoft/azure-devops-cli-extension#422]
![screen shot 2019-02-05 at 1 20 46 pm](https://user-images.githubusercontent.com/1634185/52305030-f8333380-2948-11e9-9bde-661e24ef4f4c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29493ec8-b119-457b-21c1-348a6b807884
* Version Independent ID: bf64c389-7811-b33c-6c2a-b8d69a9ec7d3
* Content: [Install the VSTS CLI](https://docs.microsoft.com/en-us/cli/vsts/install?view=vsts-cli-latest)
* Content Source: [latest/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/vsts-docs-cli-python/blob/live/latest/docs-ref-conceptual/install.md)
* Product: **vsts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by atbagga** [comment]
@mydiemho  Thank you for reporting this. 

@elbatk @geverghe Any idea who should be able to help on this? 
It seems broken for our pages only. Is this because of the repository rename or something?

**Comment by geverghe** [comment]
Not sure - let me follow up with docs team and revert back.

**Comment by dendeli-msft** [comment]
This is likely caused by a mis-configuration in the content repository. @wnjenkin is aware of the fix, we'll get this sorted out!

**Comment by wnjenkin** [comment]
This has been resolved
