### ISSUE TITLE
WIQL queries which query WorkItemLinks return nothing when using vsts-cli

### ISSUE THREAD

**Issue by tomaustin700** [Microsoft/azure-devops-cli-extension#434]
**Describe the bug**
When trying to query WorkItemLinks using WIQL no results are returned.

**To Reproduce**
vsts-cli version 0.1.3

I am using the vsts-cli to query an on premise TFS database.

1. login using vsts login
3. Run command:
I am running the query the following way, nothing is returned however when I run a similar query through TFS I get results.
`$data = vsts work item query -p 'Project' --wiql "select [System.Id] from WorkItemLinks where (Source.[System.TeamProject] = 'Project' and Source.[System.State] in ('Closed', 'Resolved')) and ([System.Links.LinkType] = 'System.LinkTypes.Related-Forward') order by [System.Title], [System.Id] mode (MustContain)" -o json
`

When running with --debug I can see the work items I would expect in the response.

**Expected behavior**
The query would return the data I expect. I can run other queries this way and they return the data I expect so it seems to be an issue when querying WorkItemLinks

**Debug logs**
Can send debug logs on request (they contain private data which I don't want to make publicly visible)

**Comment by snankani** [comment]
Thanks @tomaustin700 for using vsts-cli and raising the issue. 

We have released Azure DevOps cli as an extension to Azure CLI and vsts-cli is in support mode. All the commands in vsts-cli are ported to new Azure DevOps cli extension. Recommendation is to use the new Azure DevOps cli extension, you can find the details in below links. 

https://github.com/Microsoft/azure-devops-cli-extension/blob/master/doc/getting_started.md 
https://github.com/Microsoft/azure-devops-cli-extension/blob/master/README.md 

We are investigating on this issue and keep this issue updated with our findings.

**Comment by ishitam8** [comment]
Thanks @tomaustin700 , for finding this issue. Currently we are only supporting WorkItems returned by query result and not the WorkItemLinks results.

**Comment by tomaustin700** [comment]
@ishitam8 So if I want to run a query finding all of the work items related to another work item how would you suggest I do it?

**Comment by geverghe** [comment]
@tomaustin700 I think what you are looking for is this #125 and specifically az boards work-item relation show --expand-relations. Do have a look and let me know in which case we can continue our discussion on the thread and close this one.

**Comment by f00-beerd** [comment]
Why are we considering the vsts cli abandoned when the new cli doesn't work for people with DevOps Server 2019?

**Comment by Crono1981** [comment]
> Thanks @tomaustin700 , for finding this issue. Currently we are only supporting WorkItems returned by query result and not the WorkItemLinks results.

Shouldn't a WIQL query on WorkItemLinks cause the CLI to exit with an error code to indicate exactly that?
