### ISSUE TITLE
[Feature Request] provide an option to get the build artifacts and download them to the local machine

### ISSUE THREAD

**Issue by DonFrazier** [Microsoft/azure-devops-cli-extension#445]
I’m trying to get the build artifacts and download them using the Azure DevOps CLI.  I can get my specific build result using a command similar to this one:
 
az pipelines build show --id 171nnn --organization https://myteam.visualstudio.com --project myproject --detect off
 
Even though there are two artifacts in the azure devops UI for this build I can’t find any command that seems to help me discover and download them.  I tried “az artifacts” but it didn’t seem to have the right set of options to list these 2 artifacts. None of the “az pipelines” options seemed to show it either.  Can someone point me to the correct command?

**Comment by gauravsaralMs** [comment]
https://github.com/Microsoft/azure-devops-cli-extension/issues/81

**Comment by DonFrazier** [comment]
Thanks for the pointer.  I'd prefer a solution that uses the devops extension instead of relying on the rest APIs.  It's  a lot easier to authenticate using the Azure CLI vs. having to keep track of a PAT.  Hoping this feature can be added to this extension.

**Comment by gauravsaralMs** [comment]
@geverghe : Should this be closed as a dupe?

**Comment by geverghe** [comment]
Yes. Closing it as duplicate to #81

**Comment by DonFrazier** [comment]
The request is to be able to use Azure DevOps CLI vs. the REST interfaces.  I don't believe this is a duplicate.  Otherwise all of the Azure DevOps CLI is a duplicate too since there's already an equivalent set of REST APIs.

**Comment by gauravsaralMs** [comment]
> The request is to be able to use Azure DevOps CLI vs. the REST interfaces. I don't believe this is a duplicate. Otherwise all of the Azure DevOps CLI is a duplicate too since there's already an equivalent set of REST APIs.

@DonFrazier : https://github.com/Microsoft/azure-devops-cli-extension/issues/81 is tracking the same feature request, i.e. provide support in CLI to list and download build artifacts and that is why this is closed as dupe.
we did not closed this issue as dupe because build artifacts can be downloaded via REST API.

I would request you to follow/ collaborate at https://github.com/Microsoft/azure-devops-cli-extension/issues/81 for this feature request.

**Comment by DonFrazier** [comment]
Ok.  I thought the suggestion at #81 was "use the REST APIs" but I see that was just a workaround to get the requested info.  My bad.  Looking forward to this feature shipping.
