### ISSUE TITLE
[Bug] Unable to use contains query for repos

### ISSUE THREAD

**Issue by onlyutkarsh** [Microsoft/azure-devops-cli-extension#446]
**Describe the bug**
Trying to get the repositories with a `contains` expression. It errors out as below.

**To Reproduce**
Azure Cli Version: 
azure-cli (2.0.57)

Azure-Devops extension version: 
azure-devops (0.2.0)

1. login using az login
2. setup defaults..
3. Run command `az repos list -o table --query [?contains(name,'Infra')].{Name:name,Url:remoteUrl,Size:size}`
```
].{Name:name was unexpected at this time.
$   "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\\..\python.exe" -IBm azure.cli repos list -o table --query [?contains(name,'Infrastructure')].{Name:name,Url:remoteUrl,Size:size}
```

**Expected behavior**
A table with repositories containing the name "Infra", along with size and url

**Screenshots**
![image](https://user-images.githubusercontent.com/2685029/52915206-e9456d00-32c8-11e9-9a76-4b1d61f7e924.png)

**Debug logs**
Adding --debug errors out with similar error
![image](https://user-images.githubusercontent.com/2685029/52915136-4d1b6600-32c8-11e9-908b-0de1b040e1e2.png)

**Comment by gauravsaralMs** [comment]
`"` seems to be missing
can you try this instead
az repos list -o table --query "[?contains(name,'Infra')]"

P.S. I tried it and it seems to be working as per expectation
![image](https://user-images.githubusercontent.com/43203065/52927289-b7cbb080-335f-11e9-9b88-b21f45cd40ff.png)

**Comment by gauravsaralMs** [comment]
@onlyutkarsh : Do let me know if this works for you

**Comment by onlyutkarsh** [comment]
@gauravsaralMs Yes, enclosing filter in quote works. I am closing the issue. Thanks!
